### ISSUE TITLE
The signature in the FTDI module `write` method doesn't comply with our interface

### ISSUE THREAD

**Issue by phckopper** [balena-io-hardware/autokit-interface-sw#26]
It may return a `string` instead of `void`

https://github.com/balena-io-hardware/autokit-sw/blob/0c8b3e1e4e5a3cd9df866833dbd8e9176473f82a/lib/features/serial/implementations/ftdi/index.ts#L27-L42

https://github.com/balena-io-hardware/autokit-sw/blob/0c8b3e1e4e5a3cd9df866833dbd8e9176473f82a/lib/interfaces.d.ts#L31

We should define which path we'll consider the correct one before changing either of them.

IMHO the `write` method shouldn't perform any reading, in order to have methods that only do one thing.

**Comment by rcooke-warwick** [comment]
good point @phckopper  - write should not read. I think I did it like this originally because the demand from the appliction (e.g os test) was to "write a command over serial terminal and return the response - then check the response" - however I think they should just write a function in their test that does a write followed by a read, and the autokit should just expose seperate write and read functions

**Comment by rcooke-warwick** [comment]
will be resolved by https://github.com/balena-io-hardware/autokit-interface-sw/pull/31
